version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    assignees:
      - bunchtrail
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - bunchtrail
    open-pull-requests-limit: 5
